from enum import Enum


class WindowsEnum(Enum):
    CLR_NONE = -1

    dllhandle = 1782513664

    ILC_COLOR = 0
    ILC_COLOR16 = 16
    ILC_COLOR24 = 24
    ILC_COLOR32 = 32
    ILC_COLOR4 = 4
    ILC_COLOR8 = 8
    ILC_COLORDDB = 254
    ILC_MASK = 1

    ILD_BLEND = 4
    ILD_BLEND25 = 2
    ILD_BLEND50 = 4
    ILD_FOCUS = 2
    ILD_MASK = 16
    ILD_NORMAL = 0
    ILD_SELECTED = 4
    ILD_TRANSPARENT = 1

    IMAGE_BITMAP = 0
    IMAGE_CURSOR = 2
    IMAGE_ICON = 1

    LR_CREATEDIBSECTION = 8192
    LR_DEFAULTCOLOR = 0
    LR_DEFAULTSIZE = 64
    LR_LOADFROMFILE = 16
    LR_LOADMAP3DCOLORS = 4096
    LR_LOADTRANSPARENT = 32
    LR_MONOCHROME = 1
    LR_SHARED = 32768
    LR_VGACOLOR = 128

    NIF_ICON = 2
    NIF_INFO = 16
    NIF_MESSAGE = 1
    NIF_STATE = 8
    NIF_TIP = 4

    NIIF_ERROR = 3

    NIIF_ICON_MASK = 15

    NIIF_INFO = 1
    NIIF_NONE = 0
    NIIF_NOSOUND = 16
    NIIF_WARNING = 2

    NIM_ADD = 0
    NIM_DELETE = 2
    NIM_MODIFY = 1
    NIM_SETVERSION = 4

    TPM_BOTTOMALIGN = 32
    TPM_CENTERALIGN = 4
    TPM_LEFTALIGN = 0
    TPM_LEFTBUTTON = 0
    TPM_NONOTIFY = 128
    TPM_RETURNCMD = 256
    TPM_RIGHTALIGN = 8
    TPM_RIGHTBUTTON = 2
    TPM_TOPALIGN = 0
    TPM_VCENTERALIGN = 16
